export const MockData = [
  {
    id: 1,
    first_name: "Omar",
    last_name: "Hassan",
    first_name_arabic: "عمر",
    last_name_arabic: "حسن",
    image: "https://cdn.festilinx.com/festilinx/avatar1.png",
    nationality: "Egyptian",
    country_of_origin: "Egypt",
    country_of_residence: "UAE",
    tags: ["engineer", "team lead"],
  },
  {
    id: 2,
    first_name: "Sara",
    last_name: null,
    first_name_arabic: "سارة",
    last_name_arabic: null,
    image: null,
    nationality: "Saudi",
    country_of_origin: "Saudi Arabia",
    country_of_residence: null,
    tags: [],
  },
  {
    id: 3,
    first_name: null,
    last_name: "Khalid",
    first_name_arabic: null,
    last_name_arabic: "خالد",
    image: "https://cdn.festilinx.com/festilinx/avatar3.png",
    nationality: null,
    country_of_origin: "Jordan",
    country_of_residence: "Kuwait",
    tags: ["consultant"],
  },
  {
    id: 4,
    first_name: "Lina",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
  {
    id: 5,
    first_name: "Ali",
    last_name: "Fahmy",
    first_name_arabic: "علي",
    last_name_arabic: "فهمي",
    image: null,
    nationality: "Egyptian",
    country_of_origin: null,
    country_of_residence: null,
    tags: ["developer", "remote"],
  },
  {
    id: 6,
    first_name: "Ahme",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
    {
    id: 7,
    first_name: "Omar",
    last_name: "Hassan",
    first_name_arabic: "عمر",
    last_name_arabic: "حسن",
    image: "https://cdn.festilinx.com/festilinx/avatar1.png",
    nationality: "Egyptian",
    country_of_origin: "Egypt",
    country_of_residence: "UAE",
    tags: ["engineer", "team lead"],
  },
  {
    id: 8,
    first_name: "Sara",
    last_name: null,
    first_name_arabic: "سارة",
    last_name_arabic: null,
    image: null,
    nationality: "Saudi",
    country_of_origin: "Saudi Arabia",
    country_of_residence: null,
    tags: [],
  },
  {
    id: 9,
    first_name: null,
    last_name: "Khalid",
    first_name_arabic: null,
    last_name_arabic: "خالد",
    image: "https://cdn.festilinx.com/festilinx/avatar3.png",
    nationality: null,
    country_of_origin: "Jordan",
    country_of_residence: "Kuwait",
    tags: ["consultant"],
  },
  {
    id: 10,
    first_name: "Lina",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
  {
    id: 11,
    first_name: "Ali",
    last_name: "Fahmy",
    first_name_arabic: "علي",
    last_name_arabic: "فهمي",
    image: null,
    nationality: "Egyptian",
    country_of_origin: null,
    country_of_residence: null,
    tags: ["developer", "remote"],
  },
  {
    id: 12,
    first_name: "Ahme",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
    {
    id: 13,
    first_name: "Omar",
    last_name: "Hassan",
    first_name_arabic: "عمر",
    last_name_arabic: "حسن",
    image: "https://cdn.festilinx.com/festilinx/avatar1.png",
    nationality: "Egyptian",
    country_of_origin: "Egypt",
    country_of_residence: "UAE",
    tags: ["engineer", "team lead"],
  },
  {
    id: 14,
    first_name: "Sara",
    last_name: null,
    first_name_arabic: "سارة",
    last_name_arabic: null,
    image: null,
    nationality: "Saudi",
    country_of_origin: "Saudi Arabia",
    country_of_residence: null,
    tags: [],
  },
  {
    id: 15,
    first_name: null,
    last_name: "Khalid",
    first_name_arabic: null,
    last_name_arabic: "خالد",
    image: "https://cdn.festilinx.com/festilinx/avatar3.png",
    nationality: null,
    country_of_origin: "Jordan",
    country_of_residence: "Kuwait",
    tags: ["consultant"],
  },
  {
    id: 16,
    first_name: "Lina",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
  {
    id: 17,
    first_name: "Ali",
    last_name: "Fahmy",
    first_name_arabic: "علي",
    last_name_arabic: "فهمي",
    image: null,
    nationality: "Egyptian",
    country_of_origin: null,
    country_of_residence: null,
    tags: ["developer", "remote"],
  },
  {
    id: 18,
    first_name: "Ahme",
    last_name: "Mahmoud",
    first_name_arabic: null,
    last_name_arabic: null,
    image: "https://cdn.festilinx.com/festilinx/avatar4.png",
    nationality: "Lebanese",
    country_of_origin: null,
    country_of_residence: "Qatar",
    tags: null,
  },
];